remote_theme: pmarsceill/just-the-docs

title: Operations & SCM
description: A companion repository
baseurl: "/scm-502"
url: "https://harish-guda.github.io"

# search
search_enabled: true

# aux links
aux_links: 
  "Canvas site":
    - "//canvas.asu.edu"
aux_links_new_tab: false